# Cloudflare Pages configuration
name = "terminalvelocity"
compatibility_date = "2023-11-21"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.environment_variables]
NODE_VERSION = "18"

[[build.environment_variables.production]]
VITE_TRACKING_ENABLED = "true"

[[build.environment_variables.preview]]
VITE_TRACKING_ENABLED = "false"

[vars]
ENVIRONMENT = "production"